urdb/config/routes.rb
Urdb::Application.routes.draw do
 
 root "movies#show_all"

 get "/movies" => "movies#show_all"
 get "/movies/:id" => "movies#show", as: 'movie'

end

urdb/app/models/movie.rb
class Movie < ActiveRecord::Base
end

urdb/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

urdb/app/controllers/movies_controller.rb
class MoviesController < ApplicationController

	def show_all

		@movies = Movie.all

	end


	def show
	  @movie = Movie.find_by_id(params[:id])
	  
	end


end

urdb/app/helpers/application_helper.rb
module ApplicationHelper
end

urdb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Urdb</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

urdb/app/views/movies/show.html.erb
<html>
	<head>
		
		<%= stylesheet_link_tag "style.css" %>
	</head>
	<body>

		<div class="top">
			<h1>URDB</h1>
		</div>

			<h1><%= @movie.title %></h1>

			<p><%= @movie.description %></p>
			<%= image_tag @movie.gif_src %>

	</body>
</html>

urdb/app/views/movies/show_all.html.erb
<html>
	<head>
		<%= stylesheet_link_tag "style.css" %>
	</head>
	<body>
		<div class="top">
			<h1>URDB</h1>
		</div>

			<h2>Movies:</h2>

			<ul>
				<% @movies.each do |movie| %>
				<li><%= link_to movie.title, movie_path(movie.id) %></li>
				<% end %>
			</ul>
	</body>
</html>